apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s2aws-s3-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/k8s2aws-s3-access-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
