apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-irsa-rds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-irsa-rds
  template:
    metadata:
      labels:
        app: test-irsa-rds
    spec:
      serviceAccountName: k8s2aws-rds-sa
      containers:
        - name: test-irsa-rds
          image: ghcr.io/avnes/test-irsa:latest
