apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s2aws-ssm-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s2aws-ssm-ss
  target:
    name: k8s2aws-ssm-secret
    creationPolicy: Owner
  data:
  - secretKey: secret1
    remoteRef:
      key: /test/secret1
  - secretKey: secret2
    remoteRef:
      key: /test/secret2
