apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s2aws-ssm-ss
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: k8s2aws-ssm-sa
