apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-irsa-secretsmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-irsa-secretsmanager
  template:
    metadata:
      labels:
        app: test-irsa-secretsmanager
    spec:
      serviceAccountName: k8s2aws-secretsmanager-sa
      containers:
        - name: test-irsa-secretsmanager
          image: ghcr.io/avnes/test-irsa:latest
          # env:
          #   - name: SUPER_SECRET_1
          #     valueFrom:
          #       secretKeyRef:
          #         name: k8s2aws-secretsmanager-secret
          #         key: secret1
          #   - name: SUPER_SECRET_2
          #     valueFrom:
          #       secretKeyRef:
          #         name: k8s2aws-secretsmanager-secret
          #         key: secret2
