apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s2aws-secretsmanager-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s2aws-secretsmanager-ss
    kind: SecretStore
  target:
    name: k8s2aws-secretsmanager-secret
    creationPolicy: Owner
  data:
  - secretKey: secret1
    remoteRef:
      key: "<SOME-KEY>"
      property: "secret1"
      version: "AWSCURRENT"
  - secretKey: secret2
    remoteRef:
      key: "<SOME-KEY>"
      property: "secret2"
      version: "AWSCURRENT"
