apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s2aws-secretsmanager-ss
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: k8s2aws-secretsmanager-sa
